/*
 * Copyright 2017 Midokura SARL
 */

package moo.proyecto.entrega1;

import java.util.List;

public class DatosNiveles {

    /**
     * Vector de 3 dimensiones MAPAS[n][f][c] donde: <ul>
     * <li><pre>n</pre>: número de nivel</li>
     * <li><pre>f</pre>: fila para el nivel n</li>
     * <li><pre>c</pre>: columna para el nivel n</li>
     * </ul>
     */
    public static final char[][][] MAPAS = new char[][][]{
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#  #######  #     #".toCharArray(),
            "#        #   #    #".toCharArray(),
            "#        ######   #".toCharArray(),
            "#            #    #".toCharArray(),
            "#           #     #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#  O              #".toCharArray(),
            "#########         #".toCharArray(),
            "#########     M   #".toCharArray(),
            "###################".toCharArray()
        },

        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#           #     #".toCharArray(),
            "#            #    #".toCharArray(),
            "#  ############   #".toCharArray(),
            "#            #    #".toCharArray(),
            "#           #     #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#          #      #".toCharArray(),
            "#          #      #".toCharArray(),
            "#         ##      #".toCharArray(),
            "#     #   ##      #".toCharArray(),
            "#  O  #   ##  M   #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#    #            #".toCharArray(),
            "#   #             #".toCharArray(),
            "#  ############   #".toCharArray(),
            "#   #         #   #".toCharArray(),
            "#    #        #   #".toCharArray(),
            "#             #   #".toCharArray(),
            "#             #   #".toCharArray(),
            "#     ########    #".toCharArray(),
            "#                 #".toCharArray(),
            "#  M       K      #".toCharArray(),
            "####### ####### ###".toCharArray(),
            "############### ###".toCharArray(),
            "######O       K  K#".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "# O             M #".toCharArray(),
            "######         ####".toCharArray(),
            "## ###            #".toCharArray(),
            "## ###            #".toCharArray(),
            "## ###            #".toCharArray(),
            "## ###            #".toCharArray(),
            " # # #     ########".toCharArray(),
            "#   ##            #".toCharArray(),
            "## ###            #".toCharArray(),
            "######            #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#        #        #".toCharArray(),
            "#        #        #".toCharArray(),
            "###             ###".toCharArray(),
            "#                 #".toCharArray(),
            "#     O     M     #".toCharArray(),
            "#    ###   ###    #".toCharArray(),
            "#  ###### ######  #".toCharArray(),
            "#       # #       #".toCharArray(),
            "#       ###       #".toCharArray(),
            "####           ####".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "######       ######".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #     M    #  #".toCharArray(),
            "#   #    ###   #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #          #  #".toCharArray(),
            "#   #     O    #  #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#   K        K    #".toCharArray(),
            "#  ###      ###   #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#   O        M    #".toCharArray(),
            "######### ## # ####".toCharArray(),
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#    #       #    #".toCharArray(),
            "#    # M     #    #".toCharArray(),
            "#    #### ####    #".toCharArray(),
            "#    #  # ####    #".toCharArray(),
            "#    #  #    #    #".toCharArray(),
            "#    #  #    #    #".toCharArray(),
            "#    #  #    #    #".toCharArray(),
            "#    #### ####    #".toCharArray(),
            "#    #    #  #    #".toCharArray(),
            "#    #    #  #    #".toCharArray(),
            "#    #    #  #    #".toCharArray(),
            "#    #### #  #    #".toCharArray(),
            "#    #  #O#  #    #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#               K #".toCharArray(),
            "#            #### #".toCharArray(),
            "#                 #".toCharArray(),
            "#       #   # #   #".toCharArray(),
            "#  O    #   # #M  #".toCharArray(),
            "# ############### #".toCharArray(),
            "# ############### #".toCharArray(),
            "# #   #   #   #   #".toCharArray(),
            "#   #   #   #   # #".toCharArray(),
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#      K   K      #".toCharArray(),
            "#     ### ###     #".toCharArray(),
            "#                 #".toCharArray(),
            "#      K   K      #".toCharArray(),
            "#     ### ###     #".toCharArray(),
            "#                 #".toCharArray(),
            "#  M   K   K   O  #".toCharArray(),
            "# ####### ####### #".toCharArray(),
            "# ##   ## ##   ## #".toCharArray(),
            "# ## # ## ## # ## #".toCharArray(),
            "# ## # ##### # ## #".toCharArray(),
            "#                 #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#   K             #".toCharArray(),
            "#   K             #".toCharArray(),
            "#   K             #".toCharArray(),
            "#   KKK           #".toCharArray(),
            "#   KKK K         #".toCharArray(),
            "#  KKKK KK       M#".toCharArray(),
            "#  KKKK KK       K#".toCharArray(),
            "#  KKKKKKK     K K#".toCharArray(),
            "#  KKKKKKK   K K K#".toCharArray(),
            "# KKKKKKKKK  K K K#".toCharArray(),
            "# KKKKKKKKK  K KKK#".toCharArray(),
            "#OKKKKKKKKKKKK KKK#".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "# M          K    #".toCharArray(),
            "#### ##     ###   #".toCharArray(),
            "#######     ###   #".toCharArray(),
            "#                 #".toCharArray(),
            "#                 #".toCharArray(),
            "#   O             #".toCharArray(),
            "#  #############  #".toCharArray(),
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "###################".toCharArray()
        },
        {
            "###################".toCharArray(),
            "#                 #".toCharArray(),
            "##           K    #".toCharArray(),
            "#M ##   ###  ##  ##".toCharArray(),
            "## ##   # #     ###".toCharArray(),
            "####    # #     ###".toCharArray(),
            "#            ######".toCharArray(),
            "## ################".toCharArray(),
            "#               K #".toCharArray(),
            "## ##  #   #    # #".toCharArray(),
            "#####  # # #    # #".toCharArray(),
            "#   #  #   #      #".toCharArray(),
            "#          #   ####".toCharArray(),
            "# O  ##      ######".toCharArray(),
            "###################".toCharArray()
        },
    };
}
